---
title: "Resultados del primer conteo de monos Costa Rica 2021"
author: "Kevin Chavarría"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}

#-------------------- Paquetes --------------------

#-------------------- Archivos necesarios ---------------------



#--------------------- Íconos ---------------------



#--------------- Otros parámetros -----------------


```


```{r, include=FALSE}
#--------------- Archivos de datos ----------------

```

Pagina 1
=======================================================================
Row {data-height=1.5}
-----------------------------------------------------------------------
    
### encabezado `r  ` texto.
    
```{r, include=FALSE}
```

Row 
-----------------------------------------------------------------------
###  espacio 1 {.value-box}
```{r}


```

### espacio 2 {.value-box}
```{r}


```

### espacio 3 {.value-box}
```{r}

```

Row
-----------------------------------------------------------------------
### espacio 4 {.value-box}
```{r}

```

### espacio {.value-box}
```{r}

```

### espacio {.value-box}
```{r}

```

### espacio 
```{r}

```

Row {data-height=800}
-----------------------------------------------------------------------

### Tabla de datos
```{r}
```

Pagina 2
=======================================================================
Row {data-height=1}
-----------------------------------------------------------------------
### Última actualización de datos realizada el `r  ` texto.


Row
-----------------------------------------------------------------------

### espacio {.value-box}
```{r}

```

Row {data-width=400}
-----------------------------------------------------------------------
